---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
    exclude_fingerprints:
    - 45245e32b4d8850d55ec1afad716f318
  fixme:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.php"
exclude_paths:
- test/
